spring.application.name=todos

spring.data.mongodb.uri=mongodb://admin:secret@localhost:27017/tododb?authSource=admin
spring.data.mongodb.database=tododb
spring.data.mongodb.auto-index-creation=false

springdoc.swagger-ui.path=/docs

spring.jwt.secret=961d4651cb91305f57229adcc6043a20b051bf78f43acccceeddc85289a3419f
spring.jwt.expiration=900000
