spring.application.name=todos

spring.datasource.url=jdbc:mysql://localhost:3307/tododb?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=secret

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

springdoc.swagger-ui.path=/docs

spring.jwt.secret=961d4651cb91305f57229adcc6043a20b051bf78f43acccceeddc85289a3419f
spring.jwt.expiration=900000
